# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Comment

# Model Form Field configuration
form: $/algad/photography/models/comment/fields.yaml

# Model Class name
modelClass: Algad\Photography\Models\Comment

# Default redirect location
defaultRedirect: algad/photography/comments

# Create page
create:
    title: Create Comment
    redirect: algad/photography/comments/update/:id
    redirectClose: algad/photography/comments

# Update page
update:
    title: Edit Comment
    redirect: algad/photography/comments
    redirectClose: algad/photography/comments

# Preview page
preview:
    title: Preview Comment